IMAGE_SIZE: 512
NUM_CHANNELS: 3
PATCH_SIZE: 64
# hp['num_patches'] = (hp['image_size']**2) // (hp["patch_size"]**2)
# hp["flat_patches_shape"] = (hp["num_patches"], hp['patch_size']*hp['patch_size']*hp["num_channels"])
BATCH_SIZE: 32
LEARNING_RATE: 1e-4
EPOCHS: 30
NUM_CLASSES: 22
NUM_LAYERS: 12
HIDDEN_DIM: 512
MLP_DIM: 3072
NUM_HEADS: 12
DROPOUT_RATE: 0.1