data_ingestion:
  kaggle_dataset_slug: "obulisainaren/multi-cancer"
  kaggle_folder_name: "Multi Cancer/Multi Cancer/"
  s3_bucket: "multi-cancer-mlops-prasoon"
  s3_data_key: "Data"

data_preparation:
  s3_bucket: "multi-cancer-mlops-prasoon"
  s3_data_key: "Data"
  class_structure: "Multi Cancer/Multi Cancer/"
  split_ratio: 0.09
  local_splits_dir: "/Users/pparashar21/Desktop/Projects/CancerDetectionMLOps/Artifacts/train_test_splits/"

model_trainer:
  s3_bucket: "multi-cancer-mlops-prasoon"
  s3_model_key: "Models"
  model_name: "MultiCancerCNN.h5"
  csv_path: "MultiCancerCNN.csv"
